// spd_responder.v — SPD EEPROM Emulator
//
// Status     : [Hypothesis — designed; not yet tested on target hardware]
// Credibility: [Inference] — I2C slave + DDR3 SPD JEDEC 21C address map
//
// Purpose:
//   Emulates a DDR3 SPD EEPROM (AT24C02 or equivalent) on the SMBus.
//   Responds to I2C address 0x50 | DEVICE_ADDR[2:0] with 256 bytes of SPD data.
//
// CRITICAL — SPD DATA SOURCE:
//   The spd_rom contents MUST be generated by tools/spd-gen/generate_spd.py
//   and validated by tools/spd-gen/validate_spd.py before synthesis.
//   The ROM is initialized from an external hex file at synthesis time via
//   $readmemh. The hex file path is set by the SPD_HEX_FILE parameter.
//
//   DO NOT hard-code SPD bytes in this file.
//   DO NOT use placeholder CRC values.
//   Any SPD image with a failed CRC check will be rejected by validate_spd.py
//   and must not be used.
//
// Integration:
//   This module is driven by smbus_arbiter (inject_sda_o → inject_sda_i on arbiter,
//   inject_en_o → inject_en_i on arbiter). It monitors the smbus_monitor byte
//   stream to detect its own address and decode byte offset writes from the master.
//
// Limitations:
//   - Read-only emulation (does not support write to SPD EEPROM).
//     Write protection is the correct behavior for a read-only SPD emulator
//     because MRC does not write SPD; it only reads it.
//   - Does not implement WP pin (write protect) — always write-protected.
//   - Does not emulate the second I2C address page (0x36 + device) for thermal sensor.
//     Thermal sensor emulation is out of scope for this module.
//   - Clock stretching is not implemented. The SPD ROM must be synchronously
//     accessible within one SMBus bit period at the system clock rate.
//
// Parameter:
//   DEVICE_ADDR [2:0]: Selects which SPD EEPROM slot this instance responds to.
//     0 → A1 (0x50), 1 → A2 (0x51), 2 → B1 (0x52), 3 → B2 (0x53)
//   SPD_HEX_FILE: Path to the generated SPD hex file. Must be set at synthesis.

`default_nettype none
`timescale 1ns / 1ps

module spd_responder #(
    parameter [2:0] DEVICE_ADDR  = 3'b000,
    parameter       SPD_HEX_FILE = "INVALID_NOT_SET.hex"
    // ^^^^ SPD_HEX_FILE MUST be overridden in the top-level instantiation.
    // Synthesis will fail (or produce a zero ROM) if this is not set.
    // The hex file must be generated by tools/spd-gen/generate_spd.py
    // and validated by tools/spd-gen/validate_spd.py.
) (
    input  wire       clk_i,
    input  wire       rst_i,

    // From smbus_monitor — byte stream
    input  wire       mon_byte_valid_i,
    input  wire [7:0] mon_byte_data_i,
    input  wire       mon_is_addr_i,
    input  wire       mon_is_read_i,
    input  wire       mon_got_ack_i,
    input  wire       mon_start_i,
    input  wire       mon_stop_i,

    // SCL from monitor (needed for bit-level SDA output timing)
    input  wire       smb_scl_i,

    // To smbus_arbiter — injection interface
    output reg        inject_en_o,
    output reg        inject_sda_o,

    // Status
    output reg        active_o    // 1 = we are the addressed slave
);

    // -------------------------------------------------------------------------
    // SPD ROM — 256 bytes, initialized from hex file at synthesis
    // -------------------------------------------------------------------------
    reg [7:0] spd_rom [0:255];

    initial begin
        $readmemh(SPD_HEX_FILE, spd_rom);
    end

    // -------------------------------------------------------------------------
    // I2C slave state machine
    // -------------------------------------------------------------------------
    // State: we rely on smbus_monitor for byte/address detection.
    // When the monitor reports our address (0x50 | DEVICE_ADDR) with read=1,
    // we drive the response bytes via inject_sda_o.
    //
    // This is a simplified implementation:
    //   1. Wait for START + our address + ACK
    //   2. If read: respond with ROM[byte_ptr] byte-by-byte, advancing byte_ptr
    //      on each ACK from master
    //   3. If write (offset set): latch the next byte as byte_ptr
    //   4. On STOP or non-ACK: return to idle
    //
    // NOTE: Full I2C slave bit-banging requires driving SDA during SCL-high
    // periods on the appropriate bits. This simplified version drives inject_en_o
    // and lets smbus_arbiter handle the open-drain output. A future revision
    // must include proper bit-level timing control.

    localparam MY_ADDR_W = {1'b0, DEVICE_ADDR, 1'b0}; // Write: 0x50 | dev | 0
    localparam MY_ADDR_R = {1'b0, DEVICE_ADDR, 1'b1}; // Read:  0x50 | dev | 1

    localparam SS_IDLE      = 3'd0;
    localparam SS_RECV_PTR  = 3'd1;  // waiting for byte pointer (write transaction)
    localparam SS_SEND_BYTE = 3'd2;  // sending ROM bytes (read transaction)
    localparam SS_WAIT_ACK  = 3'd3;  // waiting for master ACK after each sent byte

    reg [2:0]  ss_state;
    reg [7:0]  byte_ptr;
    reg [7:0]  tx_byte;
    reg [3:0]  bit_idx;    // which bit of tx_byte we are sending (7 downto 0)
    reg        tx_active;

    always @(posedge clk_i) begin
        if (rst_i) begin
            ss_state    <= SS_IDLE;
            byte_ptr    <= 8'h00;
            tx_byte     <= 8'h00;
            bit_idx     <= 4'd7;
            inject_en_o <= 1'b0;
            inject_sda_o<= 1'b1;
            active_o    <= 1'b0;
            tx_active   <= 1'b0;
        end else begin
            // Handle START / STOP conditions
            if (mon_start_i) begin
                ss_state    <= SS_IDLE;
                inject_en_o <= 1'b0;
                inject_sda_o<= 1'b1;
                active_o    <= 1'b0;
                tx_active   <= 1'b0;
            end else if (mon_stop_i) begin
                ss_state    <= SS_IDLE;
                inject_en_o <= 1'b0;
                inject_sda_o<= 1'b1;
                active_o    <= 1'b0;
                tx_active   <= 1'b0;
            end else begin
                case (ss_state)
                    SS_IDLE: begin
                        if (mon_byte_valid_i && mon_is_addr_i) begin
                            // Check if this transaction addresses us
                            if (mon_byte_data_i[7:1] == {1'b0, DEVICE_ADDR} &&
                                // [Placeholder] The actual 7-bit I2C address is 0b1010_xxx
                                // where xxx = A2:A0 (device address pins).
                                // SMBus SPD EEPROM I2C address: 0x50 + DEVICE_ADDR
                                // 7-bit address field in the address byte: bits [7:1]
                                // 0x50 in 7-bit = 0b101_0000. With device: 0b101_0XXX
                                // We use [7:4] == 4'b1010 check below instead.
                                mon_byte_data_i[7:4] == 4'b1010 &&
                                mon_byte_data_i[3:1] == DEVICE_ADDR) begin
                                active_o <= 1'b1;
                                if (mon_byte_data_i[0]) begin
                                    // Read transaction: start sending ROM data
                                    tx_byte     <= spd_rom[byte_ptr];
                                    bit_idx     <= 4'd7;
                                    tx_active   <= 1'b1;
                                    inject_en_o <= 1'b1;
                                    ss_state    <= SS_SEND_BYTE;
                                end else begin
                                    // Write transaction: next byte is register pointer
                                    ss_state <= SS_RECV_PTR;
                                end
                            end
                        end
                    end

                    SS_RECV_PTR: begin
                        // Receive byte pointer from master
                        if (mon_byte_valid_i && !mon_is_addr_i) begin
                            byte_ptr <= mon_byte_data_i;
                            ss_state <= SS_IDLE; // Will get repeated START + Read next
                        end
                    end

                    SS_SEND_BYTE: begin
                        // [Placeholder — full bit-level SDA driving is not yet
                        //  implemented. This state sets inject_en_o to 1 but the
                        //  bit-level timing requires a separate SCL-tracking FSM
                        //  that is not implemented in this version.
                        //  This is marked NON_FUNCTIONAL for bit-level output.
                        //  The byte_ptr advancement on ACK is shown for completeness.]
                        inject_en_o  <= 1'b1;
                        inject_sda_o <= tx_byte[7]; // simplified: not bit-timed
                        if (mon_byte_valid_i && !mon_is_addr_i) begin
                            // Master received a byte; advance pointer
                            if (mon_got_ack_i) begin
                                byte_ptr <= byte_ptr + 8'd1;
                                tx_byte  <= spd_rom[byte_ptr + 8'd1];
                            end else begin
                                // NAK from master: end of read
                                inject_en_o <= 1'b0;
                                inject_sda_o<= 1'b1;
                                active_o    <= 1'b0;
                                tx_active   <= 1'b0;
                                ss_state    <= SS_IDLE;
                            end
                        end
                    end

                    default: ss_state <= SS_IDLE;
                endcase
            end
        end
    end

    // -------------------------------------------------------------------------
    // Design note: the bit-level SDA driving (SS_SEND_BYTE) is marked
    // [Placeholder — NON_FUNCTIONAL]. A correct implementation requires
    // tracking SCL edges and driving SDA during SCL-low periods for each bit.
    // This is a known gap. Do not enable inject_en_o on a live bus until
    // this is implemented and verified in simulation (see fpga/tb/).
    // -------------------------------------------------------------------------

endmodule
`default_nettype wire
