// spd_responder.v — SPD EEPROM Emulator (I2C Slave)
//
// Status     : [Inference — state machine designed and reviewed; unverified on hardware]
// Credibility: [Inference] — I2C slave + DDR3 SPD JEDEC 21C address map
//
// Purpose:
//   Emulates a DDR3 SPD EEPROM (AT24C02-equivalent) on the SMBus.
//   Responds to I2C address 0x50 | DEVICE_ADDR[2:0] with 256 bytes of SPD data.
//   Implements a complete I2C slave at bit level, synchronized to the raw SCL/SDA bus.
//
// CRITICAL — SPD DATA SOURCE:
//   The spd_rom contents MUST be generated by tools/spd-gen/generate_spd.py
//   and validated by tools/spd-gen/validate_spd.py before synthesis.
//   The ROM is initialized from an external hex file at synthesis time via
//   $readmemh. The hex file path is set by the SPD_HEX_FILE parameter.
//
//   DO NOT hard-code SPD bytes in this file.
//   DO NOT use placeholder CRC values.
//   Any SPD image that has not passed validate_spd.py must not be used.
//
// Integration:
//   inject_sda_o and inject_en_o drive smbus_arbiter.
//   smb_scl_i and smb_sda_i are the raw synchronized bus signals (2-FF sync upstream).
//   mon_* inputs are accepted for compatibility with smbus_monitor; they are not
//   used for bit timing in this implementation. They can be used for assertion-mode
//   cross-checking in simulation.
//
// Protocol supported:
//   Write (set byte pointer):  START + addr(W) + ACK + ptr_byte + ACK + STOP
//   Read  (sequential):        START + addr(R) + ACK + [byte + ACK]* + byte + NAK + STOP
//   Write-then-read:           START + addr(W) + ACK + ptr + ACK + Sr + addr(R) + ACK + ...
//
// Limitations:
//   - Read-only emulation. MRC does not write SPD; write pointer is accepted but no
//     write data is stored.
//   - Clock stretching not implemented. ROM lookup must complete within one bit period.
//   - No thermal sensor page (0x36 + DEVICE_ADDR) emulation.
//
// Port change vs. previous version:
//   smb_sda_i added — required for bit-level I2C slave address reception and ACK detection.
//   Previous version omitted this port and had NON_FUNCTIONAL SS_SEND_BYTE.
//
// Parameters:
//   DEVICE_ADDR [2:0]: which slot this instance services (0=A1/0x50 … 3=B2/0x53)
//   SPD_HEX_FILE: path to validated SPD ROM hex. MUST be overridden at instantiation.

`default_nettype none
`timescale 1ns / 1ps

module spd_responder #(
    parameter [2:0] DEVICE_ADDR  = 3'b000,
    parameter       SPD_HEX_FILE = "INVALID_NOT_SET.hex"
    // SPD_HEX_FILE MUST be overridden. Synthesis produces a zero ROM if not set.
    // Hex file must be produced by generate_spd.py and pass validate_spd.py.
) (
    input  wire       clk_i,
    input  wire       rst_i,

    // From smbus_monitor — accepted for compatibility / cross-check use in sim.
    // Not used for bit timing in this implementation.
    input  wire       mon_byte_valid_i,
    input  wire [7:0] mon_byte_data_i,
    input  wire       mon_is_addr_i,
    input  wire       mon_is_read_i,
    input  wire       mon_got_ack_i,
    input  wire       mon_start_i,
    input  wire       mon_stop_i,

    // Raw synchronized bus signals.
    // Both inputs must pass through a 2-FF synchronizer upstream before
    // connecting here. This module does NOT include synchronizers.
    input  wire       smb_scl_i,
    input  wire       smb_sda_i,   // ← required for bit-level I2C slave operation

    // To smbus_arbiter — open-drain injection
    output reg        inject_en_o,   // 1 = we are driving inject_sda_o onto SDA
    output reg        inject_sda_o,  // value to drive (0 = pull low, 1 = release)

    // Status
    output reg        active_o   // 1 = we are the addressed slave this transaction
);

    // -------------------------------------------------------------------------
    // SPD ROM — 256 bytes, initialized from validated hex file
    // -------------------------------------------------------------------------
    reg [7:0] spd_rom [0:255];
    initial begin
        $readmemh(SPD_HEX_FILE, spd_rom);
    end

    // -------------------------------------------------------------------------
    // I2C Slave State Machine
    //
    // States:
    //   SS_IDLE      — bus idle, waiting for START condition
    //   SS_RECV_ADDR — receiving 8 bits: 7-bit address + R/W (MSB first)
    //   SS_ADDR_ACK  — driving address ACK (SDA=0) during SCL-high of 9th clock
    //   SS_RECV_PTR  — receiving 8-bit byte pointer (write transaction)
    //   SS_SEND_BIT  — transmitting ROM data bits MSB-first, synchronized to SCL
    //   SS_WAIT_MACK — released SDA; waiting for master to drive ACK or NAK
    //
    // byte_ptr behavior:
    //   - NOT reset on START (preserved across repeated START for write-then-read)
    //   - Reset to 0x00 on STOP
    //   - Increments automatically after each acknowledged ROM byte sent
    //   - Wraps from 0xFF to 0x00 (natural 8-bit wrap = SPD page wrap)
    //
    // bit_cnt usage:
    //   - In RECV phases: 7→0, decremented on each SCL rise; action at 0 (8th bit)
    //   - In SEND_BIT from SS_ADDR_ACK: initialized to 7 (7 more bits: D6..D0)
    //     because D7 is driven directly in SS_ADDR_ACK's scl_fall handler
    //   - In SEND_BIT from SS_WAIT_MACK: initialized to 8 (all 8 bits: D7..D0)
    //   - Exit to SS_WAIT_MACK when bit_cnt decrements to 0 in SS_SEND_BIT
    // -------------------------------------------------------------------------

    localparam SS_IDLE      = 3'd0;
    localparam SS_RECV_ADDR = 3'd1;
    localparam SS_ADDR_ACK  = 3'd2;
    localparam SS_RECV_PTR  = 3'd3;
    localparam SS_SEND_BIT  = 3'd4;
    localparam SS_WAIT_MACK = 3'd5;

    reg [2:0]  ss_state;
    reg [3:0]  bit_cnt;       // 4 bits: values 0..8 needed
    reg [7:0]  rx_shift;      // shift register for received bits (addr or ptr)
    reg [7:0]  tx_shift;      // shift register for transmitted bits (ROM data)
    reg [7:0]  byte_ptr;      // current ROM read address
    reg        rw_bit;        // R/W bit from address phase: 1=read, 0=write
    reg        sda_released;  // SS_WAIT_MACK: 1 = SDA released for master ACK
    reg        ptr_ack_active;// SS_RECV_PTR: 1 = driving ACK, waiting for scl_fall

    // -------------------------------------------------------------------------
    // SCL and SDA edge detection (local — independent of smbus_monitor)
    // Operates on the synchronized inputs smb_scl_i and smb_sda_i.
    // -------------------------------------------------------------------------
    reg scl_d, sda_d;

    always @(posedge clk_i) begin
        if (rst_i) begin
            scl_d <= 1'b1;
            sda_d <= 1'b1;
        end else begin
            scl_d <= smb_scl_i;
            sda_d <= smb_sda_i;
        end
    end

    wire scl_rise_l = smb_scl_i  & ~scl_d;           // SCL 0→1
    wire scl_fall_l = ~smb_scl_i & scl_d;            // SCL 1→0
    wire start_l    = ~smb_sda_i & sda_d & smb_scl_i; // SDA falls while SCL high
    wire stop_l     = smb_sda_i & ~sda_d & smb_scl_i; // SDA rises while SCL high

    // Combinatorial: new received byte (for current SCL rise, using old rx_shift)
    wire [7:0] rx_byte_now = {rx_shift[6:0], smb_sda_i};

    // Address match check: [7:4]=1010 (AT24C02 EEPROM prefix), [3:1]=DEVICE_ADDR, [0]=R/W
    wire addr_match = (rx_byte_now[7:4] == 4'b1010) &&
                      (rx_byte_now[3:1] == DEVICE_ADDR[2:0]);

    // -------------------------------------------------------------------------
    // Main state machine
    // -------------------------------------------------------------------------
    always @(posedge clk_i) begin
        if (rst_i) begin
            ss_state      <= SS_IDLE;
            bit_cnt       <= 4'd7;
            rx_shift      <= 8'h00;
            tx_shift      <= 8'hFF;
            byte_ptr      <= 8'h00;
            rw_bit        <= 1'b0;
            sda_released  <= 1'b0;
            ptr_ack_active<= 1'b0;
            inject_en_o   <= 1'b0;
            inject_sda_o  <= 1'b1;
            active_o      <= 1'b0;

        end else if (start_l) begin
            // START (initial or repeated): reset to address receive phase.
            // byte_ptr intentionally NOT reset — preserved for write-then-read.
            ss_state      <= SS_RECV_ADDR;
            bit_cnt       <= 4'd7;
            rx_shift      <= 8'h00;
            inject_en_o   <= 1'b0;
            inject_sda_o  <= 1'b1;
            active_o      <= 1'b0;
            sda_released  <= 1'b0;
            ptr_ack_active<= 1'b0;

        end else if (stop_l) begin
            // STOP: full reset including byte_ptr.
            ss_state      <= SS_IDLE;
            inject_en_o   <= 1'b0;
            inject_sda_o  <= 1'b1;
            active_o      <= 1'b0;
            byte_ptr      <= 8'h00;
            sda_released  <= 1'b0;
            ptr_ack_active<= 1'b0;

        end else begin
            case (ss_state)

                // -----------------------------------------------------------------
                SS_IDLE: begin
                    // Waiting for START. start_l is handled above.
                end

                // -----------------------------------------------------------------
                SS_RECV_ADDR: begin
                    // Sample SDA on each SCL rising edge (MSB first into rx_shift).
                    if (scl_rise_l) begin
                        rx_shift <= rx_byte_now;
                        if (bit_cnt == 4'd0) begin
                            // 8th bit (R/W) received. rx_byte_now is the full address byte.
                            rw_bit  <= smb_sda_i;  // bit[0] = R/W
                            bit_cnt <= 4'd7;        // reset for next receive phase
                            if (addr_match) begin
                                // Our address: drive ACK (pull SDA low).
                                active_o     <= 1'b1;
                                inject_en_o  <= 1'b1;
                                inject_sda_o <= 1'b0;  // ACK = SDA low
                                ss_state     <= SS_ADDR_ACK;
                            end else begin
                                active_o <= 1'b0;
                                ss_state <= SS_IDLE;
                            end
                        end else begin
                            bit_cnt <= bit_cnt - 4'd1;
                        end
                    end
                end

                // -----------------------------------------------------------------
                SS_ADDR_ACK: begin
                    // We are holding SDA=0 (ACK) during the 9th SCL slot.
                    // On SCL falling edge (end of ACK slot): transition to data phase.
                    if (scl_fall_l) begin
                        if (rw_bit) begin
                            // Read transaction: drive D7 of first byte immediately,
                            // then SS_SEND_BIT handles D6..D0 on subsequent scl_falls.
                            inject_sda_o <= spd_rom[byte_ptr][7];
                            inject_en_o  <= 1'b1;
                            tx_shift     <= {spd_rom[byte_ptr][6:0], 1'b0};
                            bit_cnt      <= 4'd7;  // 7 remaining bits in SS_SEND_BIT
                            ss_state     <= SS_SEND_BIT;
                        end else begin
                            // Write transaction: release bus, receive byte pointer.
                            inject_en_o  <= 1'b0;
                            inject_sda_o <= 1'b1;
                            rx_shift     <= 8'h00;
                            bit_cnt      <= 4'd7;
                            ss_state     <= SS_RECV_PTR;
                        end
                    end
                end

                // -----------------------------------------------------------------
                SS_RECV_PTR: begin
                    if (!ptr_ack_active) begin
                        // Receive 8-bit byte pointer MSB-first.
                        if (scl_rise_l) begin
                            rx_shift <= rx_byte_now;
                            if (bit_cnt == 4'd0) begin
                                // Full pointer received. Latch and drive ACK.
                                byte_ptr       <= rx_byte_now;
                                inject_en_o    <= 1'b1;
                                inject_sda_o   <= 1'b0;  // ACK the pointer
                                ptr_ack_active <= 1'b1;
                            end else begin
                                bit_cnt <= bit_cnt - 4'd1;
                            end
                        end
                    end else begin
                        // Driving ACK for pointer byte. Release on SCL fall.
                        if (scl_fall_l) begin
                            inject_en_o    <= 1'b0;
                            inject_sda_o   <= 1'b1;
                            ptr_ack_active <= 1'b0;
                            ss_state       <= SS_IDLE;  // expect repeated START for read
                        end
                    end
                end

                // -----------------------------------------------------------------
                SS_SEND_BIT: begin
                    // On each SCL falling edge: output next bit from tx_shift[7]
                    // and shift left. inject_sda_o from SS_ADDR_ACK or SS_WAIT_MACK
                    // already holds the current bit being driven during SCL-high.
                    if (scl_fall_l) begin
                        inject_sda_o <= tx_shift[7];
                        inject_en_o  <= 1'b1;
                        tx_shift     <= {tx_shift[6:0], 1'b0};
                        if (bit_cnt == 4'd1) begin
                            // This is the last bit (D0 for 7-count, or D0 for 8-count).
                            // After this SCL-high, master ACK/NAK follows.
                            bit_cnt      <= 4'd0;
                            sda_released <= 1'b0;
                            ss_state     <= SS_WAIT_MACK;
                        end else begin
                            bit_cnt <= bit_cnt - 4'd1;
                        end
                    end
                end

                // -----------------------------------------------------------------
                SS_WAIT_MACK: begin
                    // Two events expected in order:
                    //   1. SCL fall (start of master ACK slot): release SDA
                    //   2. SCL rise (master drives ACK/NAK): sample and respond

                    // Event 1: release SDA (only once, before sda_released is set)
                    if (scl_fall_l && !sda_released) begin
                        inject_en_o  <= 1'b0;   // release: let master drive SDA
                        inject_sda_o <= 1'b1;
                        sda_released <= 1'b1;
                    end

                    // Event 2: sample master ACK/NAK (only after SDA released)
                    if (scl_rise_l && sda_released) begin
                        if (~smb_sda_i) begin
                            // ACK (SDA=0): advance and send next byte.
                            // byte_ptr increments; spd_rom lookup uses old byte_ptr+1
                            // (non-blocking: old value used for index on this cycle).
                            byte_ptr     <= byte_ptr + 8'd1;
                            // Drive D7 of next byte immediately on this clock.
                            // The next SCL fall will be D7's SCL period.
                            inject_sda_o <= spd_rom[byte_ptr + 8'd1][7];
                            inject_en_o  <= 1'b1;
                            tx_shift     <= {spd_rom[byte_ptr + 8'd1][6:0], 1'b0};
                            bit_cnt      <= 4'd7;   // 7 more bits (D6..D0) in SS_SEND_BIT
                            sda_released <= 1'b0;
                            ss_state     <= SS_SEND_BIT;
                        end else begin
                            // NAK (SDA=1): master is done reading. Return to idle.
                            inject_en_o  <= 1'b0;
                            inject_sda_o <= 1'b1;
                            active_o     <= 1'b0;
                            sda_released <= 1'b0;
                            ss_state     <= SS_IDLE;
                        end
                    end
                end

                default: ss_state <= SS_IDLE;
            endcase
        end
    end

    // -------------------------------------------------------------------------
    // Implementation notes
    //
    // Bit-level timing for read transactions:
    //
    //   SS_ADDR_ACK drives D7 on the scl_fall that ends the address ACK slot.
    //   SS_SEND_BIT drives D6..D0 on each subsequent scl_fall (bit_cnt=7→1).
    //   SS_WAIT_MACK holds D0 until scl_fall, then releases SDA.
    //   The master samples SDA on every SCL rising edge.
    //
    // byte_ptr advance:
    //   In SS_WAIT_MACK ACK handler, byte_ptr and spd_rom are accessed in the
    //   SAME always block cycle with non-blocking assigns. Verilog semantics:
    //   spd_rom[byte_ptr + 1] uses the OLD (pre-increment) byte_ptr value.
    //   This correctly reads the next address.
    //
    // Repeated START:
    //   start_l handler resets to SS_RECV_ADDR without clearing byte_ptr.
    //   A write transaction (ptr set) followed by repeated START followed by
    //   a read transaction will read from the byte_ptr set in the write phase.
    //
    // Testbench:
    //   fpga/tb/spd_responder_tb.v — not yet written. See salvage-audit.md.
    //   When T0.1 Stage 0 VCD is available, use it to replay real MRC SPD
    //   access patterns as regression stimulus.
    // -------------------------------------------------------------------------

endmodule
`default_nettype wire
